server:
  port: 9010
spring:
  application:
    name: article-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
      gateway:
        discovery:
          locator:
            enabled: true